name: Node.js CI

on:
    workflow_dispatch:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm install electron-packager --save-dev && npm run package-mac

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: Zalo Web.app
            path: ./dist/Zalo Web-darwin-arm64/Zalo Web.app

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: ./Zalo Web.zip*
            tag: ${{ github.ref }}
            file_glob: true
     