name: Node.js CI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm install electron-packager --save-dev && npm run package-mac

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: Zalo Web.app
            path: ./dist/Zalo Web-darwin-arm64/Zalo Web.app